# Generated by Django 4.0.5 on 2022-07-03 10:14

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_like_like_author_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.utils.get_post_image_path, verbose_name='image'),
        ),
    ]
