# Generated by Django 4.0.5 on 2022-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_followrelation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followrelation',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='from_user_follow_to_user'),
        ),
    ]
